tenant=HOME
ldap.server.type=apacheds
ldap.host=archnav-apacheds
ldap.port=10389
ldap.max.batch.size=1000
root.dn=uid=admin,ou=system
cfg.root.dn=uid=admin,ou=system
cfg.root.pw=secret
ldap.admin.root.dn=uid=admin,ou=system
ldap.admin.root.pw=secret
ldap.client.type=apache
suffix.name=example
suffix.dc=com
suffix=dc=${suffix.name},dc=${suffix.dc}
users.dn=ou=People,${suffix}
roles.dn=ou=Roles,ou=RBAC,${suffix}
policies.dn=ou=Policies,${suffix}
perms.dn=ou=Permissions,ou=RBAC,${suffix}
constraints.dn=ou=Constraints,ou=RBAC,${suffix}
userous.dn=ou=OS-U,ou=ARBAC,${suffix}
permous.dn=ou=OS-P,ou=ARBAC,${suffix}
adminroles.dn=ou=AdminRoles,ou=ARBAC,${suffix}
adminperms.dn=ou=AdminPerms,ou=ARBAC,${suffix}
groups.dn=ou=Groups,${suffix}
admin.min.conn=1
admin.max.conn=10
user.min.conn=1
user.max.conn=10
group.objectclass=configGroup
group.protocol=configProtocol
group.properties=configParameter
rfc2307=false
